services:
  web:
    image: ghcr.io/dnviti/vscode-notebooks:latest
    ports:
      - 8080:8080
      - 2222:22
    volumes:
      - ./work:/work
      - ./config:/home/${SSH_USERNAME}/.config/code-server
      - ./data:/home/${SSH_USERNAME}/.local/share/code-server
      - ./ssh:/home/vscode/.ssh